apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo94aabe73-6d86-472e-b61f-3d1cc230c56f.fullname" . }}
  labels:
    {{- include "go-echo94aabe73-6d86-472e-b61f-3d1cc230c56f.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo94aabe73-6d86-472e-b61f-3d1cc230c56f.selectorLabels" . | nindent 4 }}
