apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo4f1627e8-5121-49ed-ae6b-8254a3b66c8c.fullname" . }}
  labels:
    {{- include "go-echo4f1627e8-5121-49ed-ae6b-8254a3b66c8c.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo4f1627e8-5121-49ed-ae6b-8254a3b66c8c.selectorLabels" . | nindent 4 }}
