apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echob32706f3-f287-4a25-ad0b-4a322bcec295.fullname" . }}
  labels:
    {{- include "go-echob32706f3-f287-4a25-ad0b-4a322bcec295.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echob32706f3-f287-4a25-ad0b-4a322bcec295.selectorLabels" . | nindent 4 }}
