apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo0b76c333-fb10-43e9-971d-f396e2e01b25.fullname" . }}
  labels:
    {{- include "go-echo0b76c333-fb10-43e9-971d-f396e2e01b25.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo0b76c333-fb10-43e9-971d-f396e2e01b25.selectorLabels" . | nindent 4 }}
