apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo712e8c1d-3979-4967-b769-91b2095a4bb2.fullname" . }}
  labels:
    {{- include "go-echo712e8c1d-3979-4967-b769-91b2095a4bb2.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo712e8c1d-3979-4967-b769-91b2095a4bb2.selectorLabels" . | nindent 4 }}
