apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-app
  name: test-app
  namespace: namespace-workflow-1671053601031
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: .azurecr.io/
        name: test-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
